services:
  maczukin_appversion.version:
    class: Maczukin\AppVersionBundle\Tool\VersionTool
    calls:
      - [setContainer, ["@service_container"]]

  maczukin_appversion.twig.version:
    class: Maczukin\AppVersionBundle\Twig\Extension\Version
    arguments: ["@maczukin_appversion.version"]
    tags:
      - {name: twig.extension}
